<a href="https://colab.research.google.com/github/professional12022007/Data-Science/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import pandas as pd

In [75]:
fil = pd.read_csv("./student_data.csv", sep = ',')
print(fil)
print(fil.head())  #it gives first 5 values
print(fil.tail())  #it gives last 5 values

      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7
1               4          69            5               3
2              11          60            7               6
3               8          99            9               8
4               5          52            8               6
...           ...         ...          ...             ...
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
0                        10              62      100.00           Placed
1                         8              56      100.00           Placed
2                        10              45      100.00           Placed
3                         4              55       90.17           Placed
4                         8              40       78.82           Placed
...                     ...             ...         ...              ...
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

[10000 rows x 8 columns]
   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8
4            5          52            8               6

   assignments_completed  previous_score  exam_score placement_status
0                     10              62      100.00           Placed
1                      8              56      100.00           Placed
2                     10              45      100.00           Placed
3                      4              55       90.17           Placed
4                      8              40       78.82           Placed
      study_hours  attendance  sleep_hours  internet_usage  \
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

In [76]:
dic={
    "name":["tom","nick","krish","jack"],
    "age":[20,21,19,18],
    "roll":[1,2,3,4]
}
df=pd.DataFrame(dic)
print(df)
display(df)

    name  age  roll
0    tom   20     1
1   nick   21     2
2  krish   19     3
3   jack   18     4

    name  age  roll
0    tom   20     1
1   nick   21     2
2  krish   19     3
3   jack   18     4

In [77]:
df.shape      #it tells the number of the rows or columns  of the data

(4, 3)

In [78]:
fil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

In [79]:
print(fil.describe())

        study_hours   attendance   sleep_hours  internet_usage  \
count  10000.000000  10000.00000  10000.000000    10000.000000
mean       5.989600     69.88460      6.498500        6.062600
std        3.163589     17.61653      1.709354        3.138163
min        1.000000     40.00000      4.000000        1.000000
25%        3.000000     55.00000      5.000000        3.000000
50%        6.000000     70.00000      6.500000        6.000000
75%        9.000000     85.00000      8.000000        9.000000
max       11.000000    100.00000      9.000000       11.000000

       assignments_completed  previous_score    exam_score
count           10000.000000     10000.00000  10000.000000
mean                9.988400        64.91100     86.704207
std                 6.034145        17.50302     15.058383
min                 0.000000        35.00000     26.670000
25%                 5.000000        50.00000     76.727500
50%                10.000000        65.00000     92.120000
75%                15.000000        80.00000    100.000000
max                20.000000        95.00000    100.000000

In [80]:
fil.describe()

# There are 3 quant 25%
# Is the mean of the 1st to the median of the data
# 50% is the median of the data
# 75%
# Is the mean of the data from the median to the last

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [81]:
df.columns

Index(['name', 'age', 'roll'], dtype='object')

In [82]:
hel= pd.read_csv("./student_data.csv", sep = ',')
#print(dfo)
a = hel.tail(3) #
print(a)
b = hel.head(4) # tells the
print(b)
c = hel.shape #tells the no. of rows and column
print(c)
hel.info() #tells and provides the metadata of the file

      study_hours  attendance  sleep_hours  internet_usage  \
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed
   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8

   assignments_completed  previous_score  exam_score placement_status
0                     10              62      100.00           Placed
1                      8              56      100.00           Placed
2                     10              45      100.00           Placed
3                      4              55       90.17           Placed
(10000, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

In [83]:
# hel.tail(3)
fil.loc[hel['study_hours']==11,['study_hours','sleep_hours']].iloc[4,0]

np.int64(11)

In [84]:
hel[['study_hours','internet_usage']]

      study_hours  internet_usage
0               7               7
1               4               3
2              11               6
3               8               8
4               5               6
...           ...             ...
9995            2               7
9996            7               9
9997           10               5
9998           10               5
9999            2              11

[10000 rows x 2 columns]

In [85]:
df2=hel.loc[hel['study_hours']==11]
df2.iloc[4:8]
# ilco apni indexing banata hain
# and loc bani bani indexing pe chalta hain
fil.loc[4]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [86]:
hel.loc[hel["assignments_completed"] == 8].iloc[[1]]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
4,5,52,8,6,8,40,78.82,Placed

In [87]:
df=pd.read_csv('student_data.csv')
df[df['assignments_completed']  >3 ]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [88]:
# df["age"]=20  if df[df['assignments_completed']  >3 ] else 13
df=df.rename(columns={"assignments_completed":'assign completed'})
df

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [91]:
df = pd.read_csv('student_data.csv')
df.rename(columns={"assignments_completed":'assign completed'} , inplace =True)
df

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

The column `assignments_completed` was already renamed to `assign completed` in the output of cell `9M6-VSQ0OhMc`. The previous cell `SO5xch7ZOgg_` would not have found the original column name to rename, and thus `df` would remain unchanged. To see the current state of your DataFrame `df`:

### Example: Dropping a Column

Let's drop the `placement_status` column from our DataFrame `df` and display the first few rows of the new DataFrame.

In [92]:
df_dropped_column = df.drop('placement_status', axis=1)
display(df_dropped_column.head())

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score
0,7,56,8,7,10,62,100.00
1,4,69,5,3,8,56,100.00
2,11,60,7,6,10,45,100.00
3,8,99,9,8,4,55,90.17
4,5,52,8,6,8,40,78.82

Notice that the `placement_status` column is no longer present in `df_dropped_column`. If you check `df.head()`, you'll see the original DataFrame is still intact because `drop()` by default returns a new DataFrame rather than modifying the original one.

### Using `df.dropna()` to remove missing values

`dropna()` is used to remove rows or columns that contain `NaN` (Not a Number) values. Key parameters include:

*   `axis`: Specifies whether to drop rows (`0` or `'index'`) or columns (`1` or `'columns'`). Default is `0`.
*   `how`: Determines how to consider `NaN` values:
    *   `'any'` (default): Drop if *any* `NaN` values are present in the row/column.
    *   `'all'`: Drop only if *all* values in the row/column are `NaN`.
*   `inplace`: If `True`, modifies the DataFrame in place and returns `None`. If `False` (default), returns a new DataFrame.

Let's create a sample DataFrame with some missing values to demonstrate:

In [93]:
import numpy as np

# Create a sample DataFrame with some NaN values
data_with_nan = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 7, 8, 9, 10],
    'C': [11, 12, 13, np.nan, 15],
    'D': [16, 17, 18, 19, np.nan]
}
df_nan = pd.DataFrame(data_with_nan)
print("Original DataFrame with NaN values:")
display(df_nan)

Original DataFrame with NaN values:

     A     B     C     D
0  1.0   NaN  11.0  16.0
1  2.0   7.0  12.0  17.0
2  NaN   8.0  13.0  18.0
3  4.0   9.0   NaN  19.0
4  5.0  10.0  15.0   NaN

#### 1. Dropping rows with any `NaN` values (default behavior)

In [94]:
# By default, dropna() drops rows that contain *any* NaN values (axis=0, how='any')
df_rows_dropped = df_nan.dropna()
print("DataFrame after dropping rows with any NaN:")
display(df_rows_dropped)

DataFrame after dropping rows with any NaN:

     A    B     C     D
1  2.0  7.0  12.0  17.0

#### 2. Dropping columns with any `NaN` values

In [95]:
# To drop columns with any NaN values, set axis=1
df_cols_dropped = df_nan.dropna(axis=1)
print("DataFrame after dropping columns with any NaN:")
display(df_cols_dropped)

DataFrame after dropping columns with any NaN:

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

#### 3. Dropping rows only if all values are `NaN`

In [96]:
# Let's add a row with all NaNs to our sample DataFrame
df_nan.loc[len(df_nan)] = [np.nan, np.nan, np.nan, np.nan]
print("DataFrame with an all-NaN row:")
display(df_nan)

# Now, drop rows only if ALL values are NaN
df_all_nan_rows_dropped = df_nan.dropna(how='all')
print("DataFrame after dropping rows where all values are NaN:")
display(df_all_nan_rows_dropped)

DataFrame with an all-NaN row:

     A     B     C     D
0  1.0   NaN  11.0  16.0
1  2.0   7.0  12.0  17.0
2  NaN   8.0  13.0  18.0
3  4.0   9.0   NaN  19.0
4  5.0  10.0  15.0   NaN
5  NaN   NaN   NaN   NaN

DataFrame after dropping rows where all values are NaN:

     A     B     C     D
0  1.0   NaN  11.0  16.0
1  2.0   7.0  12.0  17.0
2  NaN   8.0  13.0  18.0
3  4.0   9.0   NaN  19.0
4  5.0  10.0  15.0   NaN

### Using `df.sort_values()` to sort a DataFrame

The `sort_values()` method sorts a DataFrame by the values of one or more columns. Key parameters are:

*   `by`: The column name(s) to sort by. Can be a single column name or a list of column names.
*   `axis`: Defaults to 0 (sort by row index labels). For sorting by column values, this is implicitly handled by `by`.
*   `ascending`: Boolean, `True` by default, for ascending order. Can be a single boolean or a list of booleans (one for each column in `by`).
*   `inplace`: If `True`, the DataFrame is modified in place and `None` is returned. If `False` (default), it returns a new sorted DataFrame.

Let's use your main `df` DataFrame for these examples.

#### 1. Sorting by a single column in ascending order (default)

In [97]:
# Sort the DataFrame by 'exam_score' in ascending order
df_sorted_asc = df.sort_values(by='exam_score')
print("DataFrame sorted by 'exam_score' (ascending):")
display(df_sorted_asc.head())

DataFrame sorted by 'exam_score' (ascending):

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
8805,1,63,4,11,6,54,26.67,Not Placed
186,1,47,5,10,0,46,26.89,Not Placed
3141,1,55,8,8,5,40,27.82,Not Placed
7566,1,58,7,3,6,38,31.41,Not Placed
9499,2,64,5,10,6,37,31.43,Not Placed

#### 2. Sorting by a single column in descending order

In [98]:
# Sort the DataFrame by 'exam_score' in descending order
df_sorted_desc = df.sort_values(by='exam_score', ascending=False)
print("DataFrame sorted by 'exam_score' (descending):")
display(df_sorted_desc.head())

DataFrame sorted by 'exam_score' (descending):

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.0,Placed
9982,6,62,6,4,20,55,100.0,Placed
9989,2,43,7,5,8,78,100.0,Placed
9992,5,100,9,2,9,62,100.0,Placed
9993,10,86,9,9,15,63,100.0,Placed

#### 3. Sorting by multiple columns

In [99]:
# Sort by 'placement_status' (ascending) then by 'exam_score' (descending)
df_sorted_multi = df.sort_values(by=['placement_status', 'exam_score'], ascending=[True, False])
print("DataFrame sorted by 'placement_status' (asc) then 'exam_score' (desc):")
display(df_sorted_multi.head())

DataFrame sorted by 'placement_status' (asc) then 'exam_score' (desc):

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
6385,4,74,4,1,10,35,69.99,Not Placed
6409,1,44,7,7,18,62,69.99,Not Placed
5810,2,62,4,3,9,48,69.97,Not Placed
4593,1,59,7,5,8,50,69.94,Not Placed
8399,1,42,8,8,7,53,69.93,Not Placed

#### 4. Using `inplace=True`

In [100]:
# Sort the DataFrame by 'study_hours' in-place
print("Original first 5 rows of df (before inplace sort):")
display(df.head())

df.sort_values(by='study_hours', inplace=True)

print("\nFirst 5 rows of df after inplace sort by 'study_hours':")
display(df.head())

Original first 5 rows of df (before inplace sort):

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

First 5 rows of df after inplace sort by 'study_hours':

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
979,1,99,9,7,14,76,94.92,Placed
9191,1,92,9,1,9,70,98.52,Placed
9190,1,57,6,4,13,39,81.96,Placed
9178,1,49,7,4,10,76,64.86,Not Placed
9175,1,72,6,2,19,62,82.22,Placed

### Using `df.sort_index()` to sort a DataFrame by its index

The `sort_index()` method sorts a DataFrame by its index labels rather than by column values. This can be useful for organizing your data based on row or column labels.

Key parameters are:

*   `axis`: Specifies whether to sort by row index (`0` or `'index'`, default) or column index (`1` or `'columns'`).
*   `ascending`: Boolean, `True` by default, for ascending order. Can be a single boolean for the chosen axis.
*   `inplace`: If `True`, the DataFrame is modified in place and `None` is returned. If `False` (default), it returns a new sorted DataFrame.

#### 1. Sorting by row index in ascending order (default)

In [101]:
# Reset the index to default integer index if it was previously sorted by a column, to better show index sorting.
# For demonstration, let's reload the original df to ensure index is not custom sorted.
df_original_index = pd.read_csv('student_data.csv')
df_original_index.rename(columns={"assignments_completed":'assign completed'} , inplace =True)

# Sort the DataFrame by its row index in ascending order (default)
df_index_sorted_asc = df_original_index.sort_index()
print("DataFrame sorted by index (ascending) - head:")
display(df_index_sorted_asc.head())
print("DataFrame sorted by index (ascending) - tail:")
display(df_index_sorted_asc.tail())

DataFrame sorted by index (ascending) - head:

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

DataFrame sorted by index (ascending) - tail:

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

#### 2. Sorting by row index in descending order

In [102]:
# Sort the DataFrame by its row index in descending order
df_index_sorted_desc = df_original_index.sort_index(ascending=False)
print("DataFrame sorted by index (descending) - head:")
display(df_index_sorted_desc.head())
print("DataFrame sorted by index (descending) - tail:")
display(df_index_sorted_desc.tail())

DataFrame sorted by index (descending) - head:

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
9999,2,70,6,11,16,52,78.96,Placed
9998,10,75,7,5,8,52,88.61,Placed
9997,10,44,8,5,10,37,95.94,Placed
9996,7,98,6,9,4,87,100.00,Placed
9995,2,58,9,7,8,88,69.31,Not Placed

DataFrame sorted by index (descending) - tail:

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
4,5,52,8,6,8,40,78.82,Placed
3,8,99,9,8,4,55,90.17,Placed
2,11,60,7,6,10,45,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
0,7,56,8,7,10,62,100.00,Placed

#### 3. Sorting by column index (i.e., column names)

In [103]:
# Sort the DataFrame by its column index (column names) in ascending order
df_cols_sorted_asc = df_original_index.sort_index(axis=1)
print("DataFrame sorted by column names (ascending) - head:")
display(df_cols_sorted_asc.head())

DataFrame sorted by column names (ascending) - head:

,assign completed,attendance,exam_score,internet_usage,placement_status,previous_score,sleep_hours,study_hours
0,10,56,100.00,7,Placed,62,8,7
1,8,69,100.00,3,Placed,56,5,4
2,10,60,100.00,6,Placed,45,7,11
3,4,99,90.17,8,Placed,55,9,8
4,8,52,78.82,6,Placed,40,8,5

In [104]:
import numpy as np
dct = {
    'name' : ['Anu', 'Riya', 'Suga', 'Jimin'],
    'age' : [22, 25, 32, 30],
    'roll' : [1, np.nan, 3, 4]
}

dF = pd.DataFrame(dct)
dF

    name  age  roll
0    Anu   22   1.0
1   Riya   25   NaN
2   Suga   32   3.0
3  Jimin   30   4.0

In [105]:
df.isnull()

,study_hours,attendance,sleep_hours,internet_usage,assign completed,previous_score,exam_score,placement_status
979,False,False,False,False,False,False,False,False
9191,False,False,False,False,False,False,False,False
9190,False,False,False,False,False,False,False,False
9178,False,False,False,False,False,False,False,False
9175,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
5446,False,False,False,False,False,False,False,False
5447,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
9988,False,False,False,False,False,False,False,False

In [ ]:
print("Output of dF.isnull():")
display(dF.isnull())

As you can see, `dF.isnull()` correctly identifies the `NaN` value in the 'roll' column for 'Riya' as `True`.

In [ ]:
print("Output of dF.notnull():")
display(dF.notnull())

As you can observe, where `dF.isnull()` showed `True` for the `NaN` value in 'Riya's 'roll' column, `dF.notnull()` shows `False` for that same cell, and `True` for all other non-missing values. This function is useful for filtering out rows or columns that have valid data.