<a href="https://colab.research.google.com/github/professional12022007/Data-Science/blob/main/PANDAS3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raja','Maini','Rahul','Ghee'],
    'age':[23,24,25,26]
})
df2=pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rani','Rani','Ganda'],
    'age':[42,45,456,56]
})

In [ ]:
result=pd.merge(df1,df2,on='id',how='outer')
result
# sare ellements a jate hain in this it is like the union of the 2 sets

   id name_x  age_x name_y  age_y
0   1   Raja   23.0    NaN    NaN
1   2  Maini   24.0    NaN    NaN
2   3  Rahul   25.0  Rahul   42.0
3   4   Ghee   26.0   Rani   45.0
4   5    NaN    NaN   Rani  456.0
5   6    NaN    NaN  Ganda   56.0

In [ ]:
result=pd.merge(df1,df2,on='id',how='inner')
result
# keval common value of both the tables are mentioned based on the both the tables
# like same id in the table

   id name_x  age_x name_y  age_y
0   3  Rahul     25  Rahul     42
1   4   Ghee     26   Rani     45

In [ ]:
result=pd.merge(df1,df2,on='id',how='left')
result
# first the table on the first table is printed and if there is not thesame id on the right table then if it does not exist in the right table then the nul value is assigned to the value
# like same id in the table

   id name_x  age_x name_y  age_y
0   1   Raja     23    NaN    NaN
1   2  Maini     24    NaN    NaN
2   3  Rahul     25  Rahul   42.0
3   4   Ghee     26   Rani   45.0

In [ ]:
result=pd.merge(df1,df2,on='id',how='right')
result
# first the table on the second table is printed and if there is not thesame id on the right table then if it does not exist in the right table then the nul value is assigned to the value
# like same id in the table

   id name_x  age_x name_y  age_y
0   3  Rahul   25.0  Rahul     42
1   4   Ghee   26.0   Rani     45
2   5    NaN    NaN   Rani    456
3   6    NaN    NaN  Ganda     56

In [ ]:
result.rename(columns={'name_x':'tablename_x'},inplace =True)
result

   id tablename_x  age_x name_y  age_y
0   3       Rahul   25.0  Rahul     42
1   4        Ghee   26.0   Rani     45
2   5         NaN    NaN   Rani    456
3   6         NaN    NaN  Ganda     56

In [ ]:
result=pd.merge(df1,df2,how='cross')
result

    id_x name_x  age_x  id_y name_y  age_y
0      1   Raja     23     3  Rahul     42
1      1   Raja     23     4   Rani     45
2      1   Raja     23     5   Rani    456
3      1   Raja     23     6  Ganda     56
4      2  Maini     24     3  Rahul     42
5      2  Maini     24     4   Rani     45
6      2  Maini     24     5   Rani    456
7      2  Maini     24     6  Ganda     56
8      3  Rahul     25     3  Rahul     42
9      3  Rahul     25     4   Rani     45
10     3  Rahul     25     5   Rani    456
11     3  Rahul     25     6  Ganda     56
12     4   Ghee     26     3  Rahul     42
13     4   Ghee     26     4   Rani     45
14     4   Ghee     26     5   Rani    456
15     4   Ghee     26     6  Ganda     56

In [ ]:
df3=pd.concat([df1,df2],axis=1)
display(df3)
df3=pd.concat([df1,df2],axis=0)
display(df3)

   id   name  age  id   name  age
0   1   Raja   23   3  Rahul   42
1   2  Maini   24   4   Rani   45
2   3  Rahul   25   5   Rani  456
3   4   Ghee   26   6  Ganda   56

   id   name  age
0   1   Raja   23
1   2  Maini   24
2   3  Rahul   25
3   4   Ghee   26
0   3  Rahul   42
1   4   Rani   45
2   5   Rani  456
3   6  Ganda   56

In [ ]:
def article_views(views: pd.DataFrame) -> pd.DataFrame:
  author=views[views['author_id']==views['viewer_id ']]
  unique_author=author['author_id'].unique()
  pd.DataFrame(unique_author)
  return pd

In [ ]:
do=pd.read_csv('student.csv')
do

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [ ]:
do.pivot_table(columns='placement_status',index='sleep_hours',values='exam_score',aggfunc='mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.509524
5                  58.306079  91.108124
6                  61.014072  91.799180
7                  59.622041  92.266900
8                  60.047371  93.059280
9                  61.181129  92.982527

In [ ]:
# columns=studyhours
# rows slleep
# values ass completed

do.pivot_table(columns='study_hours',index='sleep_hours',values='assignments_completed',aggfunc='mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844