<a href="https://colab.research.google.com/github/professional12022007/Data-Science/blob/main/PANDAS3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raja','Maini','Rahul','Ghee'],
    'age':[23,24,25,26]
})
df2=pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rani','Randi','Gandu'],
    'age':[42,45,456,56]
})

In [5]:
result=pd.merge(df1,df2,on='id',how='outer')
result
# sare ellements a jate hain in this it is like the union of the 2 sets

   id name_x  age_x name_y  age_y
0   1   Raja   23.0    NaN    NaN
1   2  Maini   24.0    NaN    NaN
2   3  Rahul   25.0  Rahul   42.0
3   4   Ghee   26.0   Rani   45.0
4   5    NaN    NaN  Randi  456.0
5   6    NaN    NaN  Gandu   56.0

In [6]:
result=pd.merge(df1,df2,on='id',how='inner')
result
# keval common value of both the tables are mentioned based on the both the tables
# like same id in the table

   id name_x  age_x name_y  age_y
0   3  Rahul     25  Rahul     42
1   4   Ghee     26   Rani     45

In [7]:
result=pd.merge(df1,df2,on='id',how='left')
result
# first the table on the first table is printed and if there is not thesame id on the right table then if it does not exist in the right table then the nul value is assigned to the value
# like same id in the table

   id name_x  age_x name_y  age_y
0   1   Raja     23    NaN    NaN
1   2  Maini     24    NaN    NaN
2   3  Rahul     25  Rahul   42.0
3   4   Ghee     26   Rani   45.0

In [8]:
result=pd.merge(df1,df2,on='id',how='right')
result
# first the table on the second table is printed and if there is not thesame id on the right table then if it does not exist in the right table then the nul value is assigned to the value
# like same id in the table

   id name_x  age_x name_y  age_y
0   3  Rahul   25.0  Rahul     42
1   4   Ghee   26.0   Rani     45
2   5    NaN    NaN  Randi    456
3   6    NaN    NaN  Gandu     56